import React from 'react';
import './styles.css'; // Arquivo CSS para estilização da tabela
import { iProduct } from '../../types/product';
import TableComponent from '../../components/Table';

const listaProducts: iProduct[] = [
  {
    id: '1',
    name: 'name',
    category: 'category',
    brand: 'brand',
    location: 'location',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
  {
    id: '1',
    name: 'string',
    category: 'string',
    brand: 'string',
    location: 'string',
    buyPrice: 10,
    sellPrice: 15,
    salesMargin: 5,
    quantity: 20,
    alertQuantity: 7,
    unitMeasurement: 'unidade',
  },
];

export default function Home() {
  return (
    <div>
      <TableComponent lista={listaProducts} />
    </div>
  );
}
